apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard
  volumeName: my-pv  # this is optional.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
